services:
  app:
    build: .
    ports:
      - "8000:8000"

  database:
    image: postgres
    hostname: posthost
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: database
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"